[project]
name = "epm-ghg-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ddgs>=9.6.1",
    "firecrawl-py>=4.5.0",
    "langchain-community>=0.4.1",
    "langchain[openai]>=1.0.2",
    "pandas>=2.3.3",
    "pydantic-settings>=2.11.0",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]

[tool.pytest.ini_options]
pythonpath = [
  ".", "app"
]
testpaths = ["tests", "app/tests"]
